name: ec333
channels:
  - defaults
dependencies:
  - basemap
  - matplotlib
  - numpy
  - nb_conda_kernels
  - pandas
  - scipy
  - statsmodels
  - pip
  - pip:
    - linearmodels
    - arch
    - autograd
